version: "3"
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - logging
    volumes:
      - /usr/share/elasticsearch/data
 
 
  kibana:
    image: kibana:latest
    ports:
      - 5601:5601
    networks:
      - logging
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
 
 
networks:
  logging:
